# Generated by Django 5.2.6 on 2025-12-10 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cruise',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relecloud.destination'),
        ),
    ]
