# Generated by Django 5.2.6 on 2025-12-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_review'),
        ('relecloud', '0005_remove_purchase_cruise_alter_purchase_destination'),
    ]

    operations = [
    ]
