# Generated by Django 5.2.6 on 2025-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_merge_20251212_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('destination_id', models.IntegerField()),
            ],
            options={
                'db_table': 'relecloud_review',
                'managed': False,
            },
        ),
    ]
