# Generated by Django 6.0 on 2025-12-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_merge_20251212_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del destino', null=True, upload_to='destinations/'),
        ),
    ]
