# Generated by Django 5.2.6 on 2025-12-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0007_add_destination_image'),
        ('relecloud', '0007_oldreview'),
    ]

    operations = [
    ]
