# Generated by Django 5.2.6 on 2025-12-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0008_merge_0007_add_destination_image_0007_oldreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldReview',
        ),
    ]
