<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-12-10 11:38
=======
# Generated by Django 5.2.7 on 2025-12-12 15:04
>>>>>>> 96c4a1d8085dc55cd4a61d72cf3c47c6915c8b8c

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relecloud', '0003_remove_inforequest_message_cruise_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to='relecloud.destination')),
            ],
        ),
    ]
<<<<<<< HEAD
=======
# Generated by Django 5.2.7 on 2025-12-12 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relecloud', '0003_remove_inforequest_message_cruise_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to='relecloud.destination')),
            ],
        ),
    ]
>>>>>>> 089ae2fcb446be135d0a687d33e6a8eeefc8a59d
=======
>>>>>>> 96c4a1d8085dc55cd4a61d72cf3c47c6915c8b8c
