# Generated by Django 5.2.6 on 2025-12-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_remove_inforequest_message_cruise_description_and_more'),
        ('reviews', '0002_alter_review_cruise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cruise',
        ),
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='relecloud.destination'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
