# Generated by Django 5.2.6 on 2025-12-12 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0009_delete_oldreview'),
        ('reviews', '0003_remove_review_cruise_review_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.IntegerField()),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('destination', models.IntegerField()),
            ],
            options={
                'db_table': 'relecloud_review',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reviews', to='relecloud.destination'),
        ),
    ]
